apiVersion: v1
kind: Service
metadata:
  name: kaiops-chat
  namespace: kaiops
spec:
  type: NodePort
  selector:
    app: kaiops-chat
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
